## Database URL (replace 'lead_db' with the name you'll create in pgAdmin)
#spring.datasource.url=jdbc:postgresql://localhost:5432/lead_db
#spring.datasource.username=postgres
#spring.datasource.password=1976
#
## Hibernate settings
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# hosting
# 1. Clean URL: Only the server address and database name. No passwords or '@' symbols here!
spring.datasource.url=jdbc:postgresql://dpg-d910d9ho3t8c73ck5cb0-a.singapore-postgres.render.com/lead_db_0no0?sslmode=require

# 2. Clean Credentials: Kept on their own dedicated lines
spring.datasource.username=parth_admin
spring.datasource.password=nWxxASlHd0osFU4Q81yfaGXq6RLTvrCF

# 3. Hibernate Configuration (Tells Java exactly how to talk to Render's database)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true